name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r backend/requirements-dev.txt # For pytest, pytest-cov
        (cd frontend && npm ci)
    
    - name: Build frontend
      run: |
        (cd frontend && npm run build)

    - name: Create .env for tests
      run: |
        echo "LLM_PROVIDER=openai" > .env
        echo "OPENAI_API_KEY=test_key_deploy" >> .env
        echo "OPENAI_MODEL=gpt-3.5-turbo" >> .env
        echo "PYTHONPATH=." >> .env
        # Minimal .env for tests; db init might also be needed if tests require a fresh db
        # Assuming run_tests.sh or tests themselves handle db setup if needed, or use existing.
        # For safety, let's add db init.
        (cd backend && python -c "from database import init_db; init_db()")

    - name: Run tests before deployment
      run: |
        chmod +x run_tests.sh
        ./run_tests.sh
    
    - name: Deploy to production
      run: |
        echo "🚀 Deploying to production..."
        echo "Frontend built successfully"
        echo "Backend dependencies installed"
        echo "All tests passed"
        echo "Ready for deployment!"
        
        # Add your deployment commands here
        # For example:
        # - Deploy to Heroku
        # - Deploy to AWS
        # - Deploy to your VPS
        # - etc.

  create-release:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          ## Changes in this Release
          - Automated release from main branch
          - All tests passed
          - Frontend and backend deployed successfully
          
          ## Test Results
          - ✅ Backend tests passed
          - ✅ Frontend tests passed
          - ✅ Integration tests passed
          - ✅ AI integration tests passed
        draft: false
        prerelease: false
